---
title: "hv_plot"
author: "Chandler Sutherland"
date: "2023-09-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(stringr)
library(ggrepel)
```


Copyright (c) Chandler Sutherland
Email: chandlersutherland@berkeley.edu

Purpose: generate a named entropy plot to demonstrate hv and non-hvNLRs
```{r}
#load in Daniil's entropy by position table 
Atha_Ent <- read_delim("C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E14\\e14_R\\Athaliana_NLR_Entropy.tsv")

#load in the gene table 
Gene_table <- read_delim("C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E14\\e14_R\\Atha_SnkMk_GeneTable.txt",delim = "\t")

#filter to just Col-0 
Col_Ent <- Atha_Ent %>% filter(str_detect(Name, 'ATHALIANA')) %>% separate(Name, c(NA, 'Gene'))
Col_table <- Gene_table %>% 
  filter(Ecotype=='ATHALIANA') %>% 
  separate(Gene, c(NA, 'Gene')) %>% 
  subset(select=c('Gene', 'Clade', 'HV')) %>% 
  distinct()

#read in common names 
names <- read_tsv("//wsl.localhost//Ubuntu//home//chandlersutherland//scratch//col0_per_domain_stats.tsv") %>% 
  dplyr::select(c('Gene', 'name')) %>% 
  distinct()

#collapse multiple names 
names[22,2]='VICTR'
names[116,2]='SOC3'

#tack common names onto the subset gene table 
Col_meta <- Col_table %>% merge(names)

#add back on to the entropy table 
named_ent <- left_join(Col_Ent, Col_meta, by=c('Gene', 'Clade')) %>% drop_na(HV)
```
Fig 1: mean entropy per NLR 
```{r}
#create a df with the mean entropy
col_seq <- named_ent %>% group_by(Gene, HV, name) %>% summarise(mean_ent = mean(Ent), 
                                                          median_ent = median(Ent),
                                                          top_10 = quantile(Ent,probs = 0.9,na.rm=T),
                                                          top_5 = quantile(Ent,probs = 0.95,na.rm=T),
                                                          top_2 = quantile(Ent,probs = 0.98,na.rm=T),
                                                          top_1 = quantile(Ent,probs = 0.99,na.rm=T))

#create a labelled histogram 
hist <- ggplot() + 
  geom_histogram(col_seq, mapping=aes(x=mean_ent, fill=as.factor(-HV)), col=I('grey'), bins=30)

real_bin <- ggplot_build(hist)$data[[1]] %>% subset(select=c(y, xmin, xmax))
breaks <- real_bin$xmin %>% unique()
plot_df <- col_seq %>% 
  mutate(bin=as.factor(as.numeric(cut(mean_ent, breaks=breaks))))%>% 
  arrange(mean_ent)
counts <- plot_df %>% group_by(bin) %>% count
label_df <- plot_df %>% filter(!is.na(name)) %>% left_join(counts, by='bin')
x <- label_df %>% subset(select=c('name', 'bin'))

mean_entropy <- ggplot() + 
  geom_histogram(plot_df, mapping=aes(x=mean_ent, fill=as.factor(-HV)), col=I('grey'))+
  xlab("Mean Entropy (bits)")+
  ylab("Number of NLRs")+
  theme_classic() +
  theme(text = element_text(size=10), 
        legend.position='none')+
  scale_fill_discrete(name ="", labels = c("hvNLR", "non-hvNLR"))

mean_entropy

ggsave(filename='C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\Outputs\\NLR Features Paper\\EMBO Submission\\Figure Panels\\fig_1a.svg', plot=mean_entropy, dpi=1000, width=87, height=55, units='mm')
```


```{r}
#save source data 
fig1_source <- plot_df %>% subset(select=c('Gene', 'HV', 'name', 'mean_ent'))
write.csv(fig1_source, file="C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\Outputs\\NLR Features Paper\\EMBO Submission\\Source Data\\Figure 1\\Col0_mean_entropy.csv")
```

EV fig 1: count vs entropy at the tenth highest entropy position 
```{r}
#create a df with the tenth highest entropy position 
col_r10 <- named_ent %>% group_by(Gene) %>% slice_max(Ent,n=10) %>% slice_min(Ent,n=1,with_ties = FALSE) %>% 
  ungroup

#create a labelled histogram 

hist <- ggplot() + 
  geom_histogram(col_r10, mapping=aes(x=Ent, fill=as.factor(-HV)), col=I('grey'), bins=30)

layer_data(hist)
real_bin <- ggplot_build(hist)$data[[1]] %>% subset(select=c(y, xmin, xmax))
breaks <- real_bin$xmin %>% unique()
plot_df <- col_r10 %>% mutate(bins2=as.factor(as.numeric(cut(Ent, breaks=breaks))))%>% arrange(Ent)
counts <- plot_df %>% group_by(bins2) %>% count
label_df <- plot_df %>% filter(!is.na(name)) %>% left_join(counts, by='bins2')

r10 <- ggplot() + 
  geom_histogram(plot_df, mapping=aes(x=Ent, fill=as.factor(-HV)), col=I('grey'), bins=30)+
  geom_vline(xintercept = 1.5,linetype="dotted")+
  geom_label_repel(label_df, 
                   mapping=aes(label=name, x=Ent, y=n, color=as.factor(-HV)), 
                   nudge_y=5, show.legend = FALSE, segment.color='grey')+
  xlab("Entropy (bits) at the 10th highest position")+
  ylab("Number of NLRs")+
  theme_classic() +
  theme(legend.position = 'none')+
  scale_fill_discrete(name ="", labels = c("HV", "non-HV"))

r10

ggsave(filename='C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\Outputs\\NLR Features Paper\\EMBO Submission\\Figure Panels\\EVfig_1.svg', plot=r10, dpi=1000, width=180, height=87, units='mm')
```


```{r}
#save source data 
ev_fig1_source <- plot_df %>% subset(select=c('Gene', 'HV', 'name', 'Ent'))
write.csv(ev_fig1_source, file="C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\Outputs\\NLR Features Paper\\EMBO Submission\\Source Data\\EV Figure 1\\Col0_tenthpos_entropy.csv")
```

