---
title: "Violin plots"
author: "Chandler Sutherland"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggsignif)
library(ggpubr)
library(ggbeeswarm)
```

```{r}
#input data 
table <- readxl::read_xlsx(path="C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E14\\all_gene_table.xlsx")

NLR_table <- table %>% filter(HV != 'all_genes')
NLR_table$HV <- factor(NLR_table$HV , levels=c("non-hv", "hv"))
```

```{r}
#expression

#determing the sample size 
NLR_table2 <- NLR_table %>% filter(!is.na(log2_TPM)) %>% group_by(HV) %>% mutate(n_exp = n()) %>% mutate(exp_label = paste0(HV,"\n", "n=",n_exp))
NLR_table2$exp_label <- factor(NLR_table2$exp_label, levels=c('non-hv\nn=105', 'hv\nn=26'))

p1 <- ggplot(NLR_table2,
       aes(x=exp_label, y=log2_TPM, fill=HV))+
    geom_violin(lwd=0.25)+
  geom_quasirandom(alpha=0.3, size=0.5)+
   ylim(0,8.8)+
   geom_signif(comparisons=list(c('non-hv\nn=105', 'hv\nn=26')), 
               map_signif_level = TRUE, y_position = c(8, 7), test=wilcox.test, textsize=2, size=0.25)+
    scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  theme_classic()+
    theme(legend.position='none', text=element_text(size=10), 
          axis.title=element_blank())+
  scale_x_discrete(labels=c('non-hv\nn=105', 'hv\nn=26'))

p1

compare_means(log2_TPM~HV, NLR_table, method = 'wilcox.test', paired = FALSE)

ggsave(filename='C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E14\\e14_R\\final_figures\\tpm.png', plot=p1, dpi='retina', width=2, height=1.5)
```

```{r}
#methylation
NLR_table3 <- NLR_table %>% filter(!is.na(meth_percentage)) %>% group_by(HV) %>% mutate(n_meth = n()) %>% mutate(meth_label = paste0(HV,"\n", "n=",n_meth))
NLR_table3$meth_label <- factor(NLR_table3$meth_label, levels=c('non-hv\nn=104', 'hv\nn=26'))

p2 <- ggplot(NLR_table3,
       aes(x=meth_label, y=meth_percentage, fill=HV))+
    geom_violin(lwd=0.25)+
  geom_quasirandom(alpha=0.3, size=0.5)+
  ylim(0,100)+
   geom_signif(comparisons=list(c('non-hv\nn=104', 'hv\nn=26')), 
               map_signif_level = TRUE, y_position = c(90, 80), test=wilcox.test, textsize=2, size=0.25)+
    scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  theme_classic()+
    theme(legend.position='none', text=element_text(size=10), axis.title=element_blank())

compare_means(meth_percentage~HV, NLR_table, method = 'wilcox.test', paired = FALSE)

ggsave(filename='C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E14\\e14_R\\final_figures\\per_meth.png', plot=p2, dpi='retina', width=2, height=1.5)
```

```{r}
#te distance 
NLR_table3 <- NLR_table %>% filter(!is.na(te_dist)) %>% group_by(HV) %>% mutate(n_te = n()) %>% mutate(te_label = paste0(HV,"\n", "n=",n_te))
NLR_table3$te_label <- factor(NLR_table3$te_label, levels=c('non-hv\nn=105', 'hv\nn=30'))

p3 <- ggplot(NLR_table3,
       aes(x=te_label, y=te_dist, fill=HV))+
    geom_violin(lwd=0.25)+
   ylim(0,35)+
  geom_quasirandom(alpha=0.3, size=0.5)+
   # geom_point(position = position_jitterdodge(), alpha=0.3, size=0.5)+
   geom_signif(comparisons=list(c('non-hv\nn=105', 'hv\nn=30')), 
               map_signif_level = TRUE, y_position = c(32, 32), test=wilcox.test, textsize=2, size=0.25)+
    scale_fill_manual(values=c('#00BFC4',  '#F8766D'))+
  theme_classic()+
    theme(legend.position='none', text=element_text(size=10), 
          axis.title=element_blank())

compare_means(te_dist~HV, NLR_table, method = 'wilcox.test', paired = FALSE)

ggsave(filename='C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E14\\e14_R\\final_figures\\te.png', plot=p3, dpi='retina', width=2, height=1.5)
```

